{
    "swagger": "2.0",
    "info": {
        "description": "EXILIMカメラのズーム操作機能を提供するAPI。",
        "version": "2.0.0",
        "title": "Camera Profile"
    },
    "consumes": [
        "application/x-www-form-urlencoded",
        "multipart/form-data"
    ],
    "paths": {
        "/zoom": {
            "put": {
                "summary": "EXILIMカメラのズーム操作を実行する",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "description": "サービスID。取得対象デバイス",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                      "name": "target",
                      "description": "撮影するカメラを識別するID",
                      "in": "formData",
                      "required": false,
                      "type": "string"
                    },
                    {
                        "name": "direction",
                        "description": "ズーム方向<br>in:ズームイン。TELE方向指定<br>out:ズームアウト。WIDE方向指定",
                        "in": "formData",
                        "required": true,
                        "type": "string",
                        "enum": [
                            "in",
                            "out"
                        ]
                    },
                    {
                        "name": "movement",
                        "description": "ズーム動作指定<br>in-start:ズーム動作開始。in-stopが指定されるまでズーム動作は続く。<br>in-stop:ズーム動作終了。in-startで開始した動作を終了させる。<br>1shot:1段階ズームを実行する。<br>max:最大値になるまでズーム動作を続ける。",
                        "in": "formData",
                        "required": true,
                        "type": "string",
                        "enum": [
                            "in-start",
                            "in-stop",
                            "1shot",
                            "max"
                        ]
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/CommonResponse"
                        }
                    }
                },
                "x-type": "one-shot"
            }
        },
        "/photoOption": {
          "get": {
            "x-type": "one-shot",
            "summary": "静止画の撮影設定を取得する。",
            "description": "静止画,動画共通の項目を含む",
            "parameters": [
              {
                "name": "serviceId",
                "in": "formData",
                "required": true,
                "type": "string"
              },
              {
                "name": "target",
                "description": "撮影するカメラを識別するID",
                "in": "formData",
                "required": false,
                "type": "string"
              }
            ],
            "responses": {
              "200": {
                "description": "",
                "schema": {
                  "$ref": "#/definitions/GetPhotoOptionResponse"
                },
                "examples": {
                  "application/json": {
                    "result": "AWB",
                    "product": "Example System",
                    "version": "1.0.0",
                    "whiteBalance": "AWV",
                    "evShift": -0.7,
                    "mirroImage": "mirror",
                    "selfTimer": 5,
                    "range": {
                      "whiteBalance": ["AWB","Daylight","Overcast","Shade","DayWhiteFluor","DaylightFluor","Tungsten"],
                      "evShift": [-2.0, -1.7, -1.3, -1.0, -0.7, -0.3, 0.0, 0.3, 0.7, 1.0, 1.3, 1.7, 2.0],
                      "mirrorImage": [
                        "normal",
                        "mirror"
                      ],
                      "selfTimer": [
                        0,
                        5,
                        10
                      ]
                    }
                  }
                }
              }
            }
          },
          "put": {
            "x-type": "one-shot",
            "summary": "静止画の撮影設定を行う",
            "description": "",
            "parameters": [
              {
                "name": "serviceId",
                "in": "formData",
                "required": true,
                "type": "string"
              },
              {
                "name": "target",
                "description": "撮影するカメラを識別するID",
                "in": "formData",
                "required": false,
                "type": "string"
              },
              {
                "name": "whiteBalance",
                "description": "ホワイトバランス",
                "in": "formData",
                "required": false,
                "type": "string"
              },
              {
                  "name": "evShift",
                  "description": "EVシフト",
                  "in": "formData",
                  "required": false,
                  "type": "number"
              },
              {
                "name": "mirrorImage",
                "description": "鏡面反転",
                "in": "formData",
                "required": false,
                "type": "string"
              },
              {
                "name": "selfTimer",
                "description": "セルフタイマー",
                "in": "formData",
                "required": false,
                "type": "integer",
                "format": "int64"
              }
            ],
            "responses": {
              "200": {
                "description": "",
                "schema": {
                  "$ref": "#/definitions/CommonResponse"
                }
              }
            }
          }
        },
        "/movieOption": {
            "get": {
                "x-type": "one-shot",
                "summary": "動画の撮影設定を取得する。",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "target",
                        "description": "撮影するカメラを識別するID",
                        "in": "formData",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/GetMovieOptionResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
                                "movieFps": 30,
                                "imageQuality": "normal",
                                "mode": "SPORTS Type1",
                                "highSpeedMode": "highspeed",
                                "pastRecordMode": "past-on",
                                "pastRecordTime": 2,
                                "recordTime": 5,
                                "range": {
					"movieFps" : [30, 60, 120, 240, 480],
	                                "imageQuality": ["normal", "economy"],
	                                "mode": ["SPORTS Type1","SPORTS Type2","SPORTS Type3","SPORTS Type4","SPORTS Type5","SPORTS Type6","SPORTS Type7","SPORTS Type8"],
	                                "highSpeedMode": ["highspeed", "normalspeed"],
	                                "pastRecordMode": ["past-on", "past-off"],
	                                "pastRecordTime": [0, 1, 2, 3, 4, 5],
                                        "recordTime": [0, 5, 10]
				}
                            }
                        }
                    }
                }
            },
            "put": {
                "x-type": "one-shot",
                "summary": "動画の撮影設定行う",
                "description": "fps設定は動画サイズと連動して設定可能範囲が変わる。",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "target",
                        "description": "撮影するカメラを識別するID",
                        "in": "formData",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "movieFps",
                        "description": "動画fps",
                        "in": "formData",
                        "required": false,
                        "type": "integer"
                    },
                    {
                        "name": "imageQuality",
                        "description": "動画画質",
                        "in": "formData",
                        "required": false,
                        "type": "string",
                        "enum": [
                            "normal",
                            "economy"
                        ]
                    },
                    {
                        "name": "mode",
                        "description": "動画撮影モード",
                        "in": "formData",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "highSpeedMode",
                        "description": "ハイスピード撮影モード",
                        "in": "formData",
                        "required": false,
                        "type": "string",
                        "enum": [
                            "highspeed",
                            "normalspeed"
                        ]
                    },
                    {
                        "name": "pastRecordMode",
                        "description": "パスト動画撮影モード",
                        "in": "formData",
                        "required": false,
                        "type": "string",
                        "enum": [
                            "past-on",
                            "past-off"
                        ]
                    },
                    {
                        "name": "pastRecordTime",
                        "description": "パスト動画撮影時間(秒)",
                        "in": "formData",
                        "required": false,
                        "type": "integer"
                    },
                    {
                      "name": "recordTime",
                      "description": "撮影時間設定",
                      "in": "formData",
                      "required": false,
                      "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/CommonResponse"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "x-type": "one-shot",
                "summary": "カメラのバージョン情報を取得する。",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                      "name": "target",
                      "description": "撮影するカメラを識別するID",
                      "in": "formData",
                      "required": false,
                      "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/GetVersionResponse"
                        }
                    }
                }
            }
        },
        "/recordingCapacity": {
            "get": {
            "x-type": "one-shot",
            "summary": "スマートデバイスからサポートしている撮影可能枚数と撮影可能時間を取得する。",
            "description": "",
            "parameters": [
                {
                    "name": "serviceId",
                    "description": "サービスID。取得対象スマートデバイス",
                    "in": "query",
                    "required": true,
                    "type": "string"
                },
                {
                  "name": "target",
                  "description": "カメラを識別するID",
                  "in": "formData",
                  "required": false,
                  "type": "string"
                }
            ],
            "responses": {
                "200": {
                    "description": "",
                    "schema": {
                       "$ref": "#/definitions/GetRecordingCapacityResponse"
                    },
                    "examples": {
                        "application/json": {
                            "result": 0,
                            "product": "EXILIM",
                            "version": "2.0.0",
                            "snapShotRecordingCapacity": [
                                10
                            ],
                            "movieRecordingCapacity": [
                                1000
                            ]
                        }
                    }
                }
            }
        }
      }
    },
    "definitions": {
      "GetPhotoOptionResponse": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/definitions/CommonResponse"
          },
          {
            "type": "object",
            "properties": {
              "whiteBalance": {
                "type": "string",
                "title": "ホワイトバランス",
                "description": "設定されているホワイトバランス"
              },
              "evShift": {
                  "type": "number",
                  "title": "EVシフト",
                  "description": "EVシフトの値"
              },
              "mirrorImage": {
                "type": "string",
                "title": "鏡面反転",
                "description": "設定されている鏡面反転"
              },
              "selfTimer": {
                "type": "number",
                "title": "セルフタイマー",
                "description": "設定されているセルフタイマー"
              },
              "Range": {
                "type": "object",
                "title": "サポートするパラメータの範囲",
                "description": "",
                "properties": {
                  "whiteBalance": {
                    "type": "array",
                    "title": "ホワイトバランス",
                    "description": "設定可能なホワイトバランス一覧",
                    "items": {
                      "type": "string"
                    }
                  },
                  "evShift": {
                    "type": "array",
                    "title": "EVシフト",
                    "description": "設定可能なEVシフト一覧",
                    "items": {
                      "type": "number"
                    }
                  },
                  "mirrorImage": {
                    "type": "array",
                    "title": "鏡面反転",
                    "description": "設定可能な鏡面反転一覧",
                    "items": {
                      "type": "integer"
                    }
                  },
                  "selfTimer": {
                    "type": "array",
                    "title": "セルフタイマー",
                    "description": "設定可能なセルフタイマー一覧",
                    "items": {
                      "type": "integer"
                    }
                  }
                }
              }
            }
          }
        ]
        },
      "GetMovieOptionResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                },
                {
                    "type": "object",
                    "properties": {
                        "movieFps": {
                            "type": "integer",
                            "title": "動画fps",
                            "description": "設定されている動画fps"
                        },
                        "imageQuality": {
                            "type": "string",
                            "title": "動画画質",
                            "description": "設定されている動画画質"
                        },
                        "mode": {
                            "type": "string",
                            "title": "動画撮影モード",
                            "description": "設定されている動画撮影モード"
                        },
                        "highSpeedMode": {
                            "type": "string",
                            "title": "ハイスピード撮影モード",
                            "description": "設定されているハイスピード撮影モード"
                        },
                        "pastRecordMode": {
                            "type": "string",
                            "title": "パスト動画撮影モード",
                            "description": "設定されているパスト動画撮影モード"
                        },
                        "pastRecordTime": {
                            "type": "integer",
                            "title": "パスト動画撮影時間",
                            "description": "設定されているパスト動画撮影時間(秒)"
                        },
                        "recordTime": {
                            "type": "string",
                            "title": "撮影時間設定",
                            "description": "設定されている撮影時間設定"
                        },
                        "Range": {
                            "type": "object",
                            "title": "サポートするパラメータの範囲",
                            "description": "",
                            "properties": {
                                "movieFps": {
                                    "type": "array",
                                    "title": "動画fps",
                                    "description": "設定可能な動画fps一覧",
                                    "items": {
                                        "type": "integer"
                                    }
                                },
                                "imageQuality": {
                                    "type": "array",
                                    "title": "動画画質",
                                    "description": "設定可能な動画画質一覧",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "mode": {
                                    "type": "array",
                                    "title": "動画撮影モード",
                                    "description": "設定可能な動画撮影モード一覧",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "highSpeedMode": {
                                    "type": "array",
                                    "title": "ハイスピード撮影モード",
                                    "description": "設定可能なハイスピード撮影モード一覧",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "pastRecordMode": {
                                    "type": "array",
                                    "title": "パスト動画撮影モード",
                                    "description": "設定可能なパスト動画撮影モード一覧",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "pastRecordTime": {
                                    "type": "array",
                                    "title": "パスト動画撮影時間",
                                    "description": "設定可能なパスト動画撮影時間一覧",
                                    "items": {
                                        "type": "integer"
                                    }
                                },
                                "recordTime": {
                                    "type": "array",
                                    "title": "撮影時間設定",
                                    "description": "撮影時間設定一覧",
                                    "items": {
                                        "type": "integer"
                                    }
                                }
                            }
                        }
                    }
                }
            ]
        },
      "GetVersionResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                },
                {
                    "type": "object",
                    "properties": {
                        "fwVersion": {
                            "type": "string",
                            "title": "カメラのバージョン情報",
                            "description": "カメラのバージョン情報 x.x.x形式"
                        }
                    }
                }
            ]
        },
      "GetRecordingCapacityResponse": {
          "type": "object",
          "allOf": [
            {
              "$ref": "#/definitions/CommonResponse"
            },
            {
              "type": "object",
              "properties": {
                "snapShotRecordingCapacity": {
                  "type": "integer",
                  "title": "撮影可能枚数",
                  "description": ""
                },
                "movieRecordingCapacity": {
                  "type": "integer",
                  "title": "撮影可能時間(秒)",
                  "description": ""
                }
              }
            }
          ]
        },
      "CommonResponse": {
            "type": "object",
            "required": [
                "product",
                "result",
                "version"
            ],
            "properties": {
                "result": {
                    "type": "integer",
                    "description": "0: 正常応答<br>0以外: 異常応答",
                    "title": "処理結果"
                },
                "product": {
                    "type": "string",
                    "description": "",
                    "title": "DeviceConnectシステムの名前"
                },
                "version": {
                    "type": "string",
                    "description": "",
                    "title": "DeviceConnectシステムのバージョン名"
                },
                "hmac": {
                    "type": "string",
                    "title": "署名",
                    "description": "レスポンスに対する署名。アプリケーション側から事前にHMACキーを共有されていた場合は必須。"
                }
            }
        }
    }
}