{
	"swagger": "2.0",
	"info": {
		"description": "EXILIMカメラによる写真撮影、動画録画または音声録音などの操作を行うAPI。",
		"version": "2.0.0",
		"title": "Media Stream Recording Profile"
	},
	"consumes": [
		"application/x-www-form-urlencoded",
		"multipart/form-data"
	],
	"paths": {
		"/mediaRecorder": {
			"get": {
                "summary": "スマートデバイスから使用可能なカメラの一覧を取得する。",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "query",
                        "description": "サービスID。取得対象スマートデバイス",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                        "$ref": "#/definitions/MediaRecorderResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
                                "recorders": [
                                    {
                                        "id": "FR100-12345678-photo",
                                        "name": "FR100-12345678-photo",
                                        "state": "inactive",
                                        "mimeType": "image/jpeg",
                                        "config": ""
                                    },
                                    {
                                        "id": "FR100-12345678-movie",
                                        "name": "FR100-12345678-movie",
                                        "state": "inactive",
                                        "mimeType": "video/x-mjpeg",
                                        "config": ""
                                    }
                                ]
                            }
                        }
                    }
                },
                "x-type": "one-shot"
            }
		},
		"/onPhoto": {
            "get": {
            "summary": "スマートデバイスの写真撮影通知イベントを取得する。",
            "description": "",
            "operationId": "mediaStreamRecordingOnPhotoGet",
            "parameters": [
            {
            "name": "serviceId",
            "in": "query",
            "description": "サービスID。取得対象スマートデバイス",
            "required": true,
            "type": "string"}
            ],
            "responses": {
            "200": {
            "description": "",
            "schema": {
            "$ref": "#/definitions/PhotoResponse"
            },
            "examples": {
            "application/json": {
            "result": 0,
            "product": "Example System",
            "version": "1.0.0",
            "photo": {
            "uri": "Dummy URI",
            "path": "Dummy Path",
            "mimeType": "image/jpeg"}}}}
            },
            "x-type": "one-shot"
            },
            "put": {
            "summary": "スマートデバイスの写真撮影通知イベントを開始する。",
            "description": "",
            "operationId": "mediaStreamRecordingOnPhotoPut",
            "parameters": [
            {
            "name": "serviceId",
            "in": "formData",
            "description": "サービスID。取得対象スマートデバイス",
            "required": true,
            "type": "string"
            },
            {
            "name": "interval",
            "in": "formData",
            "description": "デバイスプラグインがイベントを送信する間隔。",
            "required": false,
            "type": "integer",
            "format": "int64"}
            ],
            "responses": {
            "200": {
            "description": "",
            "schema": {
            "$ref": "#/definitions/EventRegistrationResponse"
            },
            "examples": {
            "application/json": {
            "result": 0,
            "product": "Example System",
            "version": "1.0.0"}}}
            },
            "x-type": "event",
            "x-event": {
            "schema": {
            "$ref": "#/definitions/PhotoEvent"
            },
            "examples": {
            "application/json": {
            "serviceId": "Host.dummyId.localhost.deviceconnect.org",
            "profile": "mediastreamrecording",
            "attribute": "onphoto",
            "photo": {
            "uri": "Dummy URI",
            "path": "Dummy Path",
            "mimeType": "image/png"}}}}
            },
            "delete": {
            "summary": "スマートデバイスの写真撮影通知イベントを停止する。",
            "description": "",
            "operationId": "mediaStreamRecordingOnPhotoDelete",
            "parameters": [
            {
            "name": "serviceId",
            "in": "query",
            "description": "サービスID。取得対象スマートデバイス",
            "required": true,
            "type": "string"}
            ],
            "responses": {
            "200": {
            "description": "",
            "schema": {
            "$ref": "#/definitions/EventUnregistrationResponse"
            },
            "examples": {
            "application/json": {
            "result": 0,
            "product": "Example System",
            "version": "1.0.0"}}}
            },
            "x-type": "event"}
		},
		"/onRecordingChange": {
            "put": {
            "summary": "動画録画イベント通知を開始する",
            "description": "実行期間中はカメラが録画を開始したら\"recording\"、録画を終了したら\"stop\"イベントを送る。",
            "parameters": [
            {
            "name": "serviceId",
            "in": "formData",
            "description": "サービスID。取得対象スマートデバイス",
            "required": true,
            "type": "string"}
            ],
            "responses": {
            "200": {
            "description": "",
            "schema": {
            "$ref": "#/definitions/EventRegistrationResponse"
            },
            "examples": {
            "application/json": {
            "result": 0,
            "product": "Example System",
            "version": "1.0.0"}}}
            },
            "x-type": "event",
            "x-event": {
            "schema": {
            "$ref": "#/definitions/RecordingStatusEvent"
            },
            "examples": {
            "application/json": {
            "serviceId": "Exilim.dummyId.localhost.deviceconnect.org",
            "profile": "mediastreamrecording",
            "attribute": "onrecordingchange",
            "media": {
            "status": "stop"}}}}
            },
            "delete": {
            "summary": "動画録画イベント通知を終了する。",
            "description": "",
            "parameters": [
            {
            "name": "serviceId",
            "in": "query",
            "description": "サービスID。取得対象スマートデバイス",
            "required": true,
            "type": "string"}
            ],
            "responses": {
            "200": {
            "description": "",
            "schema": {
            "$ref": "#/definitions/EventUnregistrationResponse"
            },
            "examples": {
            "application/json": {
            "result": 0,
            "product": "Example System",
            "version": "1.0.0"}}}
            },
            "x-type": "event"}
		},
		"/options": {
            "get": {
            "summary": "スマートデバイスからサポートしている写真撮影、動画撮影や音声録音のオプションを取得する。",
            "description": "",
            "parameters": [
            {
            "name": "serviceId",
            "in": "query",
            "description": "サービスID。取得対象スマートデバイス",
            "required": true,
            "type": "string"
            },
            {
            "name": "target",
            "in": "query",
            "description": "ターゲット。レコーダーを識別するID。省略された場合にはデフォルトのレコーダーを使用する。デバイスが音声・動画の両方のレコーダーをサポートする場合、どちらのレコーダーが使用されるかどうかはデバイスプラグイン依存とする。",
            "required": false,
            "type": "string"}
            ],
            "responses": {
            "200": {
            "description": "",
            "schema": {
            "$ref": "#/definitions/OptionsResponse"
            },
            "examples": {
            "application/json": {
            "result": 0,
            "product": "EXILIM",
            "version": "2.0.0",
            "previewMaxFrameRate": [30
            ],
            "previewSize": [
            {
            "width": 320,
            "height": 240}
            ],
            "mimeType": ["video/x-mjpeg"
            ],
            "imageSize": [
            {
            "width": 226,
            "height": 160
            },
            {
            "width": 512,
            "height": 384
            },
            {
            "width": 320,
            "height": 240
            },
            {
            "width": 640,
            "height": 480
            },
            {
            "width": 1280,
            "height": 960}
            ],
            "recordSize": {
            "width": 640,
            "height": 480}}}}
            },
            "x-type": "one-shot"
            },
            "put": {
            "summary": "スマートデバイスからサポートしている写真撮影、動画撮影や音声録音のオプションを設定する。",
            "description": "",
            "parameters": [
            {
            "name": "serviceId",
            "in": "formData",
            "description": "サービスID。取得対象スマートデバイス",
            "required": true,
            "type": "string"
            },
            {
            "name": "target",
            "in": "formData",
            "description": "ターゲット。レコーダーを識別するID。省略された場合にはデフォルトのレコーダーを使用する。デバイスが音声・動画の両方のレコーダーをサポートする場合、どちらのレコーダーが使用されるかどうかはデバイスプラグイン依存とする。",
            "required": false,
            "type": "string"
            },
            {
            "name": "previewMaxFrameRate",
            "in": "formData",
            "description": "プレビュー時の最大フレームレート。単位はfps。範囲は0.0より大きい小数値。",
            "required": false,
            "type": "number",
            "minimum": 0.0,
            "exclusiveMinimum": true
            },
            {
            "name": "mimeType",
            "in": "formData",
            "description": "MimeType。動画録画・音声録音するときのエンコードするタイプ。",
            "required": true,
            "type": "string"
            },
            {
            "name": "imageHeight",
            "in": "formData",
            "description": "撮影・録画時のサイズ(h)ピクセル",
            "required": false,
            "type": "integer"
            },
            {
            "name": "imageWidth",
            "in": "formData",
            "description": "撮影・録画時のサイズ(ｗ)ピクセル",
            "required": false,
            "type": "integer"}
            ],
            "responses": {
            "200": {
            "description": "",
            "schema": {
            "$ref": "#/definitions/RecorderControlResponse"
            },
            "examples": {
            "application/json": {
            "result": 0,
            "product": "Example System",
            "version": "1.0.0"}}}
            },
            "x-type": "one-shot"}
		},
		"/preview": {
            "put": {
            "summary": "プレビューを開始する",
            "description": "カメラのリモート撮影を開始し、ライブビュー画像を作成する。ライブビュー画像はプラグイン内でもMotionJpegとして構成され、プラグイン内に設置されたWebサーバ経由でアクセスできる。",
            "parameters": [
            {
            "name": "serviceId",
            "in": "formData",
            "required": true,
            "type": "string"
            },
            {
            "name": "target",
            "in": "formData",
            "required": false,
            "type": "string"}
            ],
            "responses": {
            "200": {
            "description": "uriにMotionJpegにアクセスするためのURLがセットされる。",
            "schema": {
            "$ref": "#/definitions/PreviewStartResponse"}}
            },
            "x-type": "streaming"
            },
            "delete": {
            "summary": "プレビューを終了する",
            "description": "カメラのリモート撮影を終了し、ライブビュー画像の作成を終了する。",
            "parameters": [
            {
            "name": "serviceId",
            "in": "query",
            "required": true,
            "type": "string"
            },
            {
            "name": "target",
            "in": "query",
            "required": false,
            "type": "string"}
            ],
            "responses": {
            "200": {
            "description": "",
            "schema": {
            "$ref": "#/definitions/PreviewStopResponse"}}
            },
            "x-type": "streaming"}
		},
		"/record": {
            "post": {
                "summary": "動画撮影を開始する",
                "description": "カメラで動画撮影を開始する。録画終了時にレスポンスが返り、その中のpathにデータ取得用のファイルパスが指定されている。カメラから状態変化の通知として onRecordingChangeのイベン通知される。",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "target",
                        "in": "formData",
                        "required": false,
                        "type": "string"
                    }
                ],
            "responses": {
                "200": {
                    "description": "撮影した動画へのファイルパスを設定する。",
                    "schema": {
                        "$ref": "#/definitions/RecordResponse"
                    }
                }
            },
            "x-type": "one-shot"}
		},
		"/stop": {
            "put": {
            "summary": "動画撮影を終了する",
            "description": "カメラの動画撮影を終了する。",
            "parameters": [
            {
            "name": "serviceId",
            "in": "formData",
            "required": true,
            "type": "string"
            },
            {
            "name": "target",
            "in": "formData",
            "required": false,
            "type": "string"}
            ],
            "responses": {
            "200": {
            "description": "",
            "schema": {
            "$ref": "#/definitions/StopResponse"}}
            },
            "x-type": "one-shot"}
		},
		"/stopSelfTimer": {
            "put": {
            "summary": "セルフタイマーをキャンセルする",
            "description": "セルフタイマーをキャンセルする。",
            "parameters": [
            {
            "name": "serviceId",
            "in": "formData",
            "required": true,
            "type": "string"
            },
            {
            "name": "target",
            "in": "formData",
            "required": false,
            "type": "string"}
            ],
            "responses": {
            "200": {
            "description": "",
            "schema": {
            "$ref": "#/definitions/CommonResponse"}}
            },
            "x-type": "one-shot"}
		},
		"/takePhoto": {
            "post": {
            "summary": "静止画を撮影する",
            "description": "カメラで静止画を撮影する。撮影後に縮小画像を端末内にコピーするので、そのままアクセスすることができる。レスポンスのuriには縮小画像のuriが設定され、pathに撮影画像本体のカメラ内でのファイル名が設定される。",
            "parameters": [
            {
            "name": "serviceId",
            "in": "formData",
            "required": true,
            "type": "string"
            },
            {
            "name": "target",
            "in": "formData",
            "required": false,
            "type": "string"}
            ],
            "responses": {
            "200": {
            "description": "撮影した画像へのファイルパスとその縮小画像へのuriを設定する。",
            "schema": {
            "$ref": "#/definitions/TakePhotoResponse"}}
            },
            "x-type": "one-shot"}
        }
	},
	"definitions": {
		"MediaRecorderResponse": {
            "allOf": [
            {
            "$ref": "#/definitions/CommonResponse"
            },
            {
            "type": "object",
            "required": ["recorders"
            ],
            "properties": {
            "recorders": {
            "type": "array",
            "description": "レコーダー情報の配列。",
            "title": "レコーダーリスト",
            "items": {
            "type": "object",
            "properties": {
            "id": {
            "type": "string",
            "description": "レコーダーを識別するID。",
            "title": "レコーダーID"
            },
            "name": {
            "type": "string",
            "description": "レコーダー名。",
            "title": "レコーダー名"
            },
            "state": {
            "type": "string",
            "description": "レコーダーの状態。",
            "title": "レコーダーの状態",
            "enum": ["inactive",
            "recording",
            "paused"
            ]
            },
            "mimeType": {
            "type": "string",
            "description": "レコーダーのエンコードするタイプ。",
            "title": "MIME Type"
            },
            "config": {
            "type": "string",
            "description": "カメラに設定がある場合には、ここに文字列としてデータが格納されている。",
            "title": "コンフィグ"}
            },
            "required": ["config",
            "id",
            "mimeType",
            "name",
            "state"
            ]}}}}
            ]
		},
		"TakePhotoResponse": {
            "allOf": [
            {
            "$ref": "#/definitions/CommonResponse"
            },
            {
            "type": "object",
            "required": ["path",
            "uri"
            ],
            "properties": {
            "uri": {
            "type": "string",
            "description": "撮影した画像の縮小画像にアクセスするurl。直前に撮影した画像のみ有効であり、次の撮影を行なうとデータは上書きされる。",
            "title": "URI"
            },
            "path": {
            "type": "string",
            "description": "撮影された写真のファイルパス。File APIのパラメータとして使用可能。こちらはカメラから直接取得するため、いつでも実行可能。",
            "title": "ファイルパス"}}}
            ]
		},
		"RecordResponse": {
            "allOf": [
                    {
                        "$ref": "#/definitions/CommonResponse"
                    }
            ]
        },
        "StopResponse": {
            "allOf": [
              {
              "$ref": "#/definitions/CommonResponse"
              },
              {
                  "type": "object",
                  "required": [
                      "path"
                  ],
                  "properties": {
                      "path": {
                          "type": "string",
                          "description": "撮影された動画のファイルパス。File APIのパラメータとして使用可能。",
                          "title": "ファイルパス"
                      }
                  }
              }
            ]
		},
		"OptionsResponse": {
            "allOf": [
            {
            "$ref": "#/definitions/CommonResponse"
            },
            {
            "required": ["mimeType"
            ],
            "properties": {
            "mimeType": {
            "type": "array",
            "description": "録画・録音する際のエンコードするタイプの一覧",
            "title": "MIME Type",
            "items": {
            "type": "string"}
            },
            "previewMaxFrameRate": {
            "type": "integer",
            "description": "プレビュー時の最大フレームレート。単位はfps。",
            "title": "Preview Max Frame Rate"
            },
            "imageSizes": {
            "type": "array",
            "description": "サポートする画像の解像度の一覧。",
            "title": "サポートするの解像度の一覧",
            "items": {
            "type": "object",
            "description": "画像の解像度。",
            "title": "解像度",
            "properties": {
            "width": {
            "type": "integer",
            "description": "画像の横幅。単位はピクセル。",
            "title": "横幅"
            },
            "height": {
            "type": "integer",
            "description": "画像の縦幅。単位はピクセル。",
            "title": "縦幅"}
            },
            "required": ["height",
            "width"
            ]}
            },
            "recordSizes": {
            "type": "object",
            "description": "画像の解像度。",
            "title": "解像度",
            "properties": {
            "width": {
            "type": "integer",
            "description": "画像の横幅。単位はピクセル。",
            "title": "横幅"
            },
            "height": {
            "type": "integer",
            "description": "画像の縦幅。単位はピクセル。",
            "title": "縦幅"}
            },
            "required": ["height",
            "width"
            ]
            },
            "previewSizes": {
            "type": "array",
            "description": "プレビューで利用可能な解像度の一覧。録音の場合、またはプレビューを 提供しない場合は省略可。プラグイン側でリサイズすることでサポートするサイズも含めてよい。",
            "title": "プレビュー時の解像度の一覧",
            "items": {
            "type": "object",
            "description": "画像の解像度。",
            "title": "解像度",
            "properties": {
            "width": {
            "type": "integer",
            "description": "画像の横幅。単位はピクセル。",
            "title": "横幅"
            },
            "height": {
            "type": "integer",
            "description": "画像の縦幅。単位はピクセル。",
            "title": "縦幅"}
            },
            "required": ["height",
            "width"
            ]}}}}
            ]
		},
		"PhotoResponse": {
            "allOf": [
            {
            "$ref": "#/definitions/CommonResponse"
            },
            {
            "$ref": "#/definitions/PhotoInfo"}
            ]
		},
		"PhotoEvent": {
            "allOf": [
            {
            "$ref": "#/definitions/CommonEvent"
            },
            {
            "$ref": "#/definitions/PhotoInfo"}
            ]
        },
        "PhotoInfo": {
            "type": "object",
            "required": ["photo"
            ],
            "properties": {
            "photo": {
            "type": "object",
            "description": "撮影された写真データ。",
            "title": "写真データ",
            "properties": {
            "uri": {
            "type": "string",
            "description": "takePhoto APIと同じ",
            "title": "URI"
            },
            "path": {
            "type": "string",
            "description": "takePhoto APIと同じ",
            "title": "ファイルパス"
            },
            "mimeType": {
            "type": "string",
            "description": "撮影された写真のMIME Type。動画・音声を識別するために使用する。",
            "title": "MIME Type"}
            },
            "required": ["mimeType",
            "path"
            ]}}
		},
		"PreviewStartResponse": {
            "allOf": [
            {
            "$ref": "#/definitions/CommonResponse"
            },
            {
            "type": "object",
            "required": ["uri"
            ],
            "properties": {
            "uri": {
            "type": "string",
            "description": "開始したプレビューの配信用URI。形式はMotionJPEGとする。",
            "title": "プレビュー配信URI"}}}
            ]
		},
		"PreviewStopResponse": {
            "allOf": [
            {
            "$ref": "#/definitions/CommonResponse"}
            ]
		},
		"RecordingStatusEvent": {
            "allOf": [
            {
            "$ref": "#/definitions/CommonEvent"
            },
            {
            "$ref": "#/definitions/RecordingStatusInfo"}
            ]
		},
		"RecordingStatusInfo": {
            "type": "object",
            "required": ["media"
            ],
            "properties": {
            "media": {
            "type": "object",
            "description": "レコーディング情報",
            "title": "レコーディング情報",
            "properties": {
            "status": {
            "type": "string",
            "description": "レコーディングの状態を識別する文字列。開始時にrecording、セルフタイマー開始時にcaptureReadyが設定され、 通常、セルフタイマー終了時ともにstopが設定される",
            "title": "レコーディングの状態",
            "enum": ["recording",
            "stop",
            "pause",
            "resume",
            "mutetrack",
            "unmutetrack",
            "error",
            "warning"
            ]
		},
		"path": {
		"type": "string",
		"description": "撮影された動画のファイルパス。File APIのパラメータとして使用可能。非API要因で録画が終了した場合に有効",
		"title": "ファイルパス"}
		},
		"required": ["status"
		]}}
		},
		"RecorderControlResponse": {
            "allOf": [
            {
            "$ref": "#/definitions/CommonResponse"}
            ]
            },
        "EventRegistrationResponse": {
            "allOf": [
            {
            "$ref": "#/definitions/CommonResponse"}
            ]
        },
        "EventUnregistrationResponse": {
            "allOf": [
            {
            "$ref": "#/definitions/CommonResponse"}
            ]
		},
		"CommonResponse": {
            "type": "object",
            "required": [
                "product",
                "result",
                "version"
            ],
            "properties": {
                "result": {
                    "type": "integer",
                    "description": "0:  正常応答<br>0以外:  異常応答",
                    "title": "処理結果"
                },
                "product": {
                    "type": "string",
                    "description": "",
                    "title": "DeviceConnectシステムの名前"
                },
                "version": {
                    "type": "string",
                    "description": "",
                    "title": "DeviceConnectシステムのバージョン名"
                },
                "hmac": {
                    "type": "string",
                    "description": "アプリケーション側から事前にHMACキーを共有されていた場合は必須。",
                    "title": "レスポンスに対する署名"
                }
            }
		},
		"CommonEvent": {
            "type": "object",
            "required": ["attribute",
            "profile",
            "serviceId"
            ],
            "properties": {
            "serviceId": {
            "type": "string",
            "description": "",
            "title": "サービスID"
            },
            "profile": {
            "type": "string",
            "description": "",
            "title": "プロファイル名"
            },
            "attribute": {
            "type": "string",
            "description": "",
            "title": "アトリビュート名"}}
        }
    }
}